# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote = true
  end

  config.vm.define :loadBalancer do |loadBalancer|
    loadBalancer.vm.box = "bento/ubuntu-22.04"
    loadBalancer.vm.network :private_network, ip: "192.168.100.3"
    loadBalancer.vm.hostname = "loadBalancer"
  end

  config.vm.define :backend1 do |backend1|
    backend1.vm.box = "bento/ubuntu-22.04"
    backend1.vm.network :private_network, ip: "192.168.100.4"
    backend1.vm.hostname = "backend1"
  end

  config.vm.define :backend2 do |backend2|
    backend2.vm.box = "bento/ubuntu-22.04"
    backend2.vm.network :private_network, ip: "192.168.100.5"
    backend2.vm.hostname = "backend2"
  end

  config.vm.define :backend3 do |backend3|
    backend3.vm.box = "bento/ubuntu-22.04"
    backend3.vm.network :private_network, ip: "192.168.100.6"
    backend3.vm.hostname = "backend3"
  end
end
