# -- mode: ruby --
# vi: set ft=ruby :

Vagrant.configure("2") do |config|  
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "servidorUbuntu"
  config.vm.network :private_network, ip: "192.168.100.3"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    apt-get install -y curl
    curl -L https://omnitruck.chef.io/install.sh | bash
  SHELL

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "chef/cookbooks"
    chef.add_recipe "nginx_setup"
    chef.arguments = "--chef-license accept"
  end
end
